name: ddpg_net_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23  
  - pytorch=2.0.1
  - torchvision=0.15  
  - matplotlib=3.7.1
  - pip
  - pip:
      - pygame==2.6.1  

